### ISSUE TITLE
WebP image support

### ISSUE THREAD

**Issue by y-luis** [datocms/product-roadmap#172]
**Is your feature request related to a problem? Please describe.**
File field does not show preview when using a WebP image.

**Describe the solution you'd like**
I would like the image preview is shown when uploading a WebP image the same as for other image formats.

**Additional context**
![image](https://user-images.githubusercontent.com/8008773/61368598-1b61f780-a886-11e9-9aa0-89753cdf3c37.png)

**Comment by stefanoverna** [comment]
Sorry but Imgix right now does not support transformations if the source format is WebP.. so.. we cannot do anything about that :( Furthermore, since webp is not a format that is supported in every browser/context, it would not be advisable to store them as source. Better use PNGs! 
If you use PNGs, the [auto=format transformation](https://docs.imgix.com/apis/url/auto/auto#format) will automatically determine whether the image can be served in a better format by a process called automatic content negotiation.
